print("Mi perfil")
nombre = input("Escribe tu nombre: ")
print("Hola", nombre)
edad = int (input("Ingresa tu edad:"))
print("Tu edad es:", edad)
print("Felicidades")
print("Estoy colaborando en este proyecto")
print("Colaboro nuevamente con este línea de código :)")